# Generated by Django 4.2.13 on 2024-06-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='text_param',
            field=models.TextField(blank=True, null=True),
        ),
    ]
